services:
  - type: web
    name: jam-md
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: SESSION_ID
        value: ""
      - key: OWNER_NUMBER
        value: "256765309986"
      - key: BOT_NAME
        value: "JAM-MD"
      - key: COMMAND_MODE
        value: "public"
      - key: TIMEZONE
        value: "Africa/Kampala"
      - key: MONGO_URL
        value: ""
      - key: POSTGRES_URL
        value: ""
      - key: MYSQL_URL
        value: ""
      - key: DB_URL
        value: ""
