import { generateImage } from '../lib/imageGen.js';

  export default {
      command: 'imagine',
      aliases: ['gen', 'generate', 'draw', 'paint'],
      category: 'ai',
      description: 'Generate an AI image from a text description',
      usage: '.imagine <description>',
      async handler(sock, message, args, context) {
          const chatId = context.chatId || message.key.remoteJid;
          const prompt = args.join(' ').trim();

          if (!prompt) {
              return sock.sendMessage(chatId, {
                  text: `🎨 *Usage:* .imagine <description>\n\n` +
                      `*Examples:*\n` +
                      `• .imagine Ice Spice performing on stage\n` +
                      `• .imagine a detailed map of Africa\n` +
                      `• .imagine a sunset over Kampala Uganda\n` +
                      `• .imagine a futuristic city at night\n\n` +
                      `_Powered by Pollinations AI — free, no key needed_`
              }, { quoted: message });
          }

          await sock.sendMessage(chatId, {
              text: `🎨 Generating...\n_"${prompt}"_`
          }, { quoted: message });

          try {
              await sock.presenceSubscribe(chatId);
              await sock.sendPresenceUpdate('composing', chatId);
          } catch { }

          try {
              const buf = await generateImage(prompt);
              await sock.sendMessage(chatId, {
                  image: buf,
                  caption: `🎨 *${prompt}*\n_Generated by Pollinations AI_`
              }, { quoted: message });
          } catch (err) {
              await sock.sendMessage(chatId, {
                  text: `❌ Image generation failed: ${err.message}\nTry a different description.`
              }, { quoted: message });
          }
      }
  };
  