import fetch from 'node-fetch';

const API_BASE = process.env.AIRTEL_CONFIG_URL
    ? process.env.AIRTEL_CONFIG_URL.replace('/api/airtel', '')
    : 'https://b7a31e27-b2db-4aba-baf4-c04898f6ecb4-00-125u8d6u0oodo.sisko.replit.dev';

export default {
    command: 'jez',
    aliases: ['v2ray', 'airtelv2', 'configs', 'freeconfigs'],
    category: 'tools',
    description: 'Get TCP-tested working v2ray configs for JZ PRO VPN on Airtel Uganda',
    usage: '.jez',
    async handler(sock, message, args, context) {
        const chatId = context.chatId || message.key.remoteJid;

        try {
            await sock.sendMessage(chatId, {
                text: '🔍 *Fetching tested v2ray configs...*\n\nEvery config is TCP-checked before sending. Please wait up to 30 seconds.'
            }, { quoted: message });

            const res = await fetch(`${API_BASE}/api/jez`, {
                headers: { 'User-Agent': 'JAM-MD-Bot/1.0' },
                timeout: 60000
            });

            if (!res.ok) {
                return await sock.sendMessage(chatId, {
                    text: `❌ *Server error (${res.status})*\n\nTry again in a few minutes.`
                }, { quoted: message });
            }

            const data = await res.json();

            if (!data.sample || data.sample.length === 0) {
                return await sock.sendMessage(chatId, {
                    text: '⚠️ *No working configs found right now.*\n\nAll tested servers appear to be down. Try again in 10–15 minutes.'
                }, { quoted: message });
            }

            const configs = data.sample;
            const protocols = data.protocols || [];
            const updatedAt = data.updated
                ? new Date(data.updated).toLocaleString('en-UG', { timeZone: 'Africa/Kampala' })
                : 'Just now';

            // Build file content
            const fileContent = [
                '# Tested v2ray configs — generated by JAM-MD bot',
                `# TCP-verified: ${data.count} working servers found`,
                `# Updated: ${updatedAt}`,
                `# Usage: Paste any line into JZ PRO VPN > Custom Setup > V2Ray Tunnel`,
                '',
                ...configs
            ].join('\n');

            const fileBuffer = Buffer.from(fileContent, 'utf-8');

            const caption =
                `📡 *Tested v2ray Configs* ✅\n\n` +
                `🔬 *TCP-verified:* ${data.count} working servers\n` +
                `📦 *Sending:* ${configs.length} configs\n` +
                `🕒 *Tested at:* ${updatedAt}\n\n` +
                `*How to use with JZ PRO VPN:*\n` +
                `1️⃣ Open the file & copy any config line\n` +
                `2️⃣ Open JZ PRO VPN\n` +
                `3️⃣ Tap *Custom Setup* → *V2Ray Tunnel*\n` +
                `4️⃣ Paste the line in the box\n` +
                `5️⃣ Tap *SAVE* → *START*\n\n` +
                `💡 Try the next line if one doesn't work on Airtel UG\n` +
                `_Powered by ${context?.config?.botName || 'JAM-MD'}_`;

            await sock.sendMessage(chatId, {
                document: fileBuffer,
                mimetype: 'text/plain',
                fileName: `tested_configs_${new Date().toISOString().slice(0, 10)}.txt`,
                caption
            }, { quoted: message });

            // Send first 3 inline for quick paste
            const lines = configs.slice(0, 3).map((c, i) => {
                const proto = protocols[i] ? `[${protocols[i].toUpperCase()}]` : '';
                return `*${i + 1}.* ${proto}\n\`${c.slice(0, 100)}${c.length > 100 ? '...' : ''}\``;
            });

            await sock.sendMessage(chatId, {
                text: `📋 *Quick Copy — first 3 tested configs:*\n\n${lines.join('\n\n')}`
            }, { quoted: message });

        } catch (error) {
            console.error('[Jez Plugin Error]', error);
            await sock.sendMessage(chatId, {
                text: `❌ *Error fetching configs*\n\n${error.message || 'Unknown error'}\n\nContact the bot owner.`
            }, { quoted: message });
        }
    }
};
