// Free SSH account fetcher for HTTP Custom (Uganda/East Africa)

  const SSH_PROVIDERS = [
      {
          name: 'FastSSH',
          servers: [
              { id: 'sg1-fastssh', region: 'Singapore' },
              { id: 'us1-fastssh', region: 'USA' },
              { id: 'de1-fastssh', region: 'Germany' },
          ],
          createUrl: (server) => `https://www.fastssh.com/page/create-ssh-account/server/${server}/`,
          body: (user, pass) => `username=${user}&password=${pass}&repassword=${pass}`,
          parseHost: (html) => html.match(/([\d]{1,3}\.){3}[\d]{1,3}/)?.[0],
          parsePort: (html) => html.match(/Port.*?(\d{2,5})/)?.[1] || '22',
          parseWs: (html) => html.match(/WebSocket.*?(80|443|8080|8880)/i)?.[1] || '80',
      },
      {
          name: 'SpeedSSH',
          servers: [
              { id: 'sg1.speedssh.com', region: 'Singapore' },
              { id: 'us1.speedssh.com', region: 'USA' },
          ],
          createUrl: (server) => `https://www.speedssh.com/create-ssh/${server}/`,
          body: (user, pass) => `username=${user}&password=${pass}&repassword=${pass}`,
          parseHost: (html) => html.match(/([\d]{1,3}\.){3}[\d]{1,3}/)?.[0],
          parsePort: (html) => html.match(/Port.*?(\d{2,5})/)?.[1] || '22',
          parseWs: (html) => html.match(/WebSocket.*?(80|443|8080|8880)/i)?.[1] || '80',
      },
  ];

  const AIRTEL_PAYLOADS = [
      { name: 'WhatsApp SNI (try first)', host: 'web.whatsapp.com', payload: 'GET / HTTP/1.1[crlf]Host: web.whatsapp.com[crlf]Upgrade: websocket[crlf][crlf]' },
      { name: 'WhatsApp CDN', host: 'mmg.whatsapp.net', payload: 'GET / HTTP/1.1[crlf]Host: mmg.whatsapp.net[crlf]Upgrade: websocket[crlf][crlf]' },
      { name: 'Google APIs', host: 'clients3.google.com', payload: 'GET / HTTP/1.1[crlf]Host: clients3.google.com[crlf]Upgrade: websocket[crlf][crlf]' },
      { name: 'Facebook Free', host: '0.facebook.com', payload: 'GET / HTTP/1.1[crlf]Host: 0.facebook.com[crlf]Upgrade: websocket[crlf][crlf]' },
      { name: 'HTTP CONNECT', host: 'web.whatsapp.com', payload: 'CONNECT web.whatsapp.com:443 HTTP/1.1[crlf]Host: web.whatsapp.com[crlf][crlf]' },
      { name: 'Airtel Africa Portal', host: 'airtelafrica.com', payload: 'GET / HTTP/1.1[crlf]Host: airtelafrica.com[crlf]Upgrade: websocket[crlf][crlf]' },
  ];

  function randomStr(len) {
      const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
      return Array.from({ length: len }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
  }

  async function tryCreate(provider, serverObj) {
      try {
          const user = 'jam' + randomStr(6);
          const pass = randomStr(8) + 'A1!';
          const url = provider.createUrl(serverObj.id);
          const controller = new AbortController();
          const tid = setTimeout(() => controller.abort(), 20000);
          const res = await fetch(url, {
              method: 'POST',
              signal: controller.signal,
              headers: {
                  'Content-Type': 'application/x-www-form-urlencoded',
                  'User-Agent': 'Mozilla/5.0 (Linux; Android 12) AppleWebKit/537.36 Chrome/120',
                  'Referer': url,
                  'Accept': 'text/html,application/xhtml+xml',
              },
              body: provider.body(user, pass),
          });
          clearTimeout(tid);
          if (!res.ok) return null;
          const html = await res.text();
          if (!html.includes(user) && !html.match(/([\d]{1,3}\.){3}[\d]{1,3}/)) return null;
          const host = provider.parseHost(html);
          if (!host) return null;
          return {
              provider: provider.name,
              region: serverObj.region,
              host,
              port: provider.parsePort(html),
              wsPort: provider.parseWs(html),
              username: user,
              password: pass,
              expiry: '7 days',
          };
      } catch { return null; }
  }

  function buildFile(accounts, payloads) {
      const date = new Date().toISOString().split('T')[0];
      const L = [
          `# Free SSH Accounts for HTTP Custom — Airtel Uganda — ${date}`,
          '# Generated by JAM-MD Bot',
          '# IMPORTANT: Use port 80 or 443 in HTTP Custom (Airtel blocks port 22)',
          '',
          '# ============================================================',
          '# SSH ACCOUNTS',
          '# ============================================================',
          '',
      ];

      if (accounts.length > 0) {
          accounts.forEach((a, i) => {
              L.push(`# --- Account ${i + 1} [${a.provider} - ${a.region}] ---`);
              L.push(`Host:       ${a.host}`);
              L.push(`Port:       ${a.port}   ← change to 80 or 443 for Airtel UG`);
              L.push(`WS Port:    ${a.wsPort}`);
              L.push(`Username:   ${a.username}`);
              L.push(`Password:   ${a.password}`);
              L.push(`Expires:    ${a.expiry}`);
              L.push('');
          });
      } else {
          L.push('# Could not auto-fetch accounts (sites have anti-bot protection)');
          L.push('# Visit one of these to get a free SSH account in 30 seconds:');
          L.push('');
          L.push('#  1. fastssh.com       (best - choose Singapore, enable WebSocket)');
          L.push('#  2. speedssh.com      (good for Africa)');
          L.push('#  3. sshocean.net      (free 7-day accounts)');
          L.push('#  4. createssh.com     (simple signup)');
          L.push('#  5. goodssh.com       (has WebSocket support)');
          L.push('');
          L.push('# When creating: choose Singapore or USA server + enable WebSocket');
          L.push('');
      }

      L.push('# ============================================================');
      L.push('# PAYLOAD TEMPLATES FOR AIRTEL UGANDA');
      L.push('# Paste one into: HTTP Custom → Config → Payload');
      L.push('# ============================================================');
      L.push('');
      payloads.forEach((p, i) => {
          L.push(`# PAYLOAD ${i + 1} — ${p.name}`);
          L.push(`# Bug Host / SNI: ${p.host}`);
          L.push(p.payload);
          L.push('');
      });

      L.push('# ============================================================');
      L.push('# FULL SETUP GUIDE — HTTP CUSTOM FOR AIRTEL UGANDA');
      L.push('# ============================================================');
      L.push('# Step 1: Open HTTP Custom app');
      L.push('# Step 2: SSH tab:');
      L.push('#   SSH Host   → Host from account above');
      L.push('#   SSH Port   → 80 or 443  (NOT 22, Airtel blocks it)');
      L.push('#   Username   → username from above');
      L.push('#   Password   → password from above');
      L.push('# Step 3: Config tab:');
      L.push('#   Payload    → paste PAYLOAD 1 (WhatsApp SNI)');
      L.push('#   SNI / Host → web.whatsapp.com');
      L.push('#   Proxy IP   → 127.0.0.1');
      L.push('#   Proxy Port → 8888');
      L.push('# Step 4: Tap CONNECT → watch LOG tab');
      L.push('# Step 5: "Connection reset"? Try PAYLOAD 2, then 3...');
      L.push('# Step 6: Connected but no internet? Change SNI to match payload host');
      L.push('# Step 7: Still failing? Get a new SSH account and repeat');
      L.push('#');
      L.push('# Run .ssh again for fresh accounts anytime');

      return L.join('\n');
  }

  export default {
      command: 'ssh',
      aliases: ['getssh', 'sshaccount', 'freessh', 'airtel', 'ugconfig', 'hcsetup'],
      category: 'tools',
      description: 'Get free SSH accounts + Airtel Uganda HTTP Custom payloads',
      usage: '.ssh',
      async handler(sock, message, args, context) {
          const chatId = context.chatId || message.key.remoteJid;
          const date = new Date().toISOString().split('T')[0];

          await sock.sendMessage(chatId, {
              text: '🔐 Fetching free SSH accounts from multiple providers...\n_This takes up to 20 seconds_'
          }, { quoted: message });

          try { await sock.presenceSubscribe(chatId); await sock.sendPresenceUpdate('composing', chatId); } catch { }

          // Try all provider+server combinations in parallel
          const attempts = SSH_PROVIDERS.flatMap(p => p.servers.slice(0, 2).map(s => tryCreate(p, s)));
          const results = await Promise.all(attempts);

          // Deduplicate by host
          const seen = new Set();
          const accounts = results.filter(r => {
              if (!r || seen.has(r.host)) return false;
              seen.add(r.host); return true;
          });

          const fileContent = buildFile(accounts, AIRTEL_PAYLOADS);

          await sock.sendMessage(chatId, {
              document: Buffer.from(fileContent),
              fileName: `ssh-airtel-uganda-${date}.txt`,
              mimetype: 'text/plain',
              caption: accounts.length > 0
                  ? `✅ *${accounts.length} SSH account(s) fetched!*\n\n` +
                    `File contains:\n` +
                    `• SSH credentials ready to paste\n` +
                    `• 6 Airtel Uganda payload templates\n` +
                    `• Full step-by-step setup guide\n\n` +
                    `⚠️ Use port *80 or 443* — Airtel blocks port 22`
                  : `📋 *Setup guide + payload templates ready*\n\n` +
                    `Auto-fetch was blocked (these sites have anti-bot protection)\n\n` +
                    `File contains:\n` +
                    `• List of sites to get free SSH in 30 seconds\n` +
                    `• 6 Airtel Uganda payload templates\n` +
                    `• Full step-by-step setup guide\n\n` +
                    `Best site: *fastssh.com* → 30 sec signup\n` +
                    `Pick Singapore server + enable WebSocket`
          }, { quoted: message });
      }
  };
  